FROM public.ecr.aws/nginx/nginx:alpine
WORKDIR /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY robots.txt /usr/share/nginx/html/robots.txt
COPY style.css /usr/share/nginx/html/style.css
RUN echo "✅ Build completed successfully from public ECR nginx:alpine"
